# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "xhci_hcd" ];
  boot.kernelModules = [ "kvm-intel" "uvcvideo" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3757a7eb-4aaf-451f-ab5d-1501979f825a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0084-331B";
      fsType = "vfat";
    };
  
  fileSystems."/data" = 
    { device = "/dev/disk/by-uuid/48f62c66-fe19-48f6-9e7a-d6338671fec0";
      fsType = "ext4";
    };
  swapDevices = [ 
    { device = "/dev/disk/by-label/swap"; }
  ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
